server.port=9090
spring.application.name=PatchlyDemo
spring.datasource.url=jdbc:postgresql://d6q0avv5gffc73dtltk0-a.oregon-postgres.render.com/patchly_kb
spring.datasource.username=patchly_kb_user
spring.datasource.password=S0AT7budm32uGLAkni6CW6lRLHnKwpYp
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always